# Generated by Django 4.0.2 on 2022-03-02 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregistration',
            name='name',
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='phone',
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
