# Generated by Django 4.0.2 on 2022-03-02 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='username',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='main.userregistration'),
        ),
    ]
