# Generated by Django 4.0.2 on 2022-03-02 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_portfolio_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('portfoliostockid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=100)),
                ('companyname', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('exchangetype', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('targetprice', models.CharField(max_length=100)),
                ('portfolioname', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='main.portfolio')),
            ],
        ),
    ]
