# Generated by Django 4.0.2 on 2022-03-02 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_stock'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stock',
            new_name='StockPortfolio',
        ),
    ]
