# Generated by Django 4.0.2 on 2022-03-04 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_stock_stockportfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='MutualFundPortfolio',
            fields=[
                ('portfoliomfid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('units', models.CharField(max_length=100)),
                ('nav', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('foliono', models.CharField(max_length=100)),
                ('portfolioname', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='main.portfolio')),
            ],
        ),
    ]
