# Generated by Django 4.0.2 on 2022-03-16 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_mutualfundportfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('watchlistid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('addeddate', models.CharField(max_length=100)),
                ('addedprice', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('username', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='main.userregistration')),
            ],
        ),
    ]
